[package]
name = "colorpop-rust"
version = "0.1.0"
authors = ["tom"]
edition = "2018"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[dependencies]
sdl2 = "0.34.2"
rand = "0.7.3"